# -*- coding: utf-8 -*-
"""DAPO_TRL _code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aF3LxEMmLl0fCyA5yVBAkU_Rgsy3dsh5

<center>

<div style="text-align:center;">
<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/aligntune/refs/heads/main/assets/aligntune-banner.png" width="690"></a>

<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/docs.png" width="150"></a>
<a href="https://discord.gg/dSB62Q7A"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/discord.png" width="150"></a>
</a>

<a href="https://arxiv.org/abs/2511.02802"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/lexsilogo.png" width="200"></a>
</div>

Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/Lexsi-Labs/aligntune">Github</a> </i> ⭐

To run this, press "*Runtime*" and press "*Run all*" on a Google Colab instance!
</center>

## Setup Aligntune Repository
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Lexsi-Labs/aligntune.git
# %cd aligntune/
!pip install -e .

"""## Setup, Configuration, and Helper Functions"""

# Cell 1: Setup, Configuration, and Helper Functions
import os
import gc
import json
import torch
from pathlib import Path
from aligntune.core.backend_factory import create_rl_trainer
from aligntune.eval.runner import EvalConfig, run_eval
from huggingface_hub import login

# Login to Hugging Face
login(token="")

def cleanup_memory():
    """Aggressive memory cleanup"""
    gc.collect()
    torch.cuda.empty_cache()
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    print("✓ Memory cleaned")

def run_evaluation(model_path, dataset_name, dataset_split, column_mapping,
                   output_dir, eval_name, use_lora=False, base_model=None):
    """Run evaluation on test set with Pass@K metrics."""
    dataset_short = dataset_name.split('/')[-1]
    print(f"\n>>> Evaluating {eval_name.upper()} model on {dataset_short.upper()}...")

    eval_config = EvalConfig(
        # Model & Hardware
        model_path=model_path,
        output_dir=f"{output_dir}/eval_{eval_name}_{dataset_short}",
        device="cuda",

        # Task & Metrics
        task_type="code",
        metrics=["pass_at_k"],
        k_list=[1, 2, 5, 10],

        # Dataset
        dataset_name=dataset_name,
        dataset_config=None,
        split=dataset_split,
        column_mapping=column_mapping,

        # Generation Parameters
        max_length=512,
        temperature=0.2,
        batch_size=8,
        max_samples=100,
        num_samples=10,

        # PEFT / Adapters
        use_lora=use_lora,
        base_model=base_model,
    )

    results = run_eval(eval_config)

    print(f"✓ {eval_name.upper()} on {dataset_short.upper()}:")
    print(f"  Pass@1: {results.get('pass_at_1', 0.0)*100:.2f}%")
    print(f"  Pass@10: {results.get('pass_at_10', 0.0)*100:.2f}%")

    cleanup_memory()

    return {
        'pass_at_1': results.get('pass_at_1', 0.0),
        'pass_at_2': results.get('pass_at_2', 0.0),
        'pass_at_5': results.get('pass_at_5', 0.0),
        'pass_at_10': results.get('pass_at_10', 0.0),
        'total_samples': results.get('total', 100),
        'output_dir': eval_config.output_dir
    }

# Configuration
BASE_MODEL = "meta-llama/Llama-3.2-3B-Instruct"
TRAIN_DATASET = "google-research-datasets/mbpp"
OUTPUT_DIR = "output/grpo_mbpp_comparison"

print("="*90)
print("GRPO TRAINING WITH MBPP - CODE GENERATION EVALUATION")
print("="*90)
print("\nThis pipeline will:")
print("  1. Train a GRPO model with mbpp_reward (code execution + test cases)")
print("  2. Evaluate Base Model and GRPO on MBPP and HumanEval")
print("  3. Evaluate Pass@K (k=1,2,5,10)")
print("  4. Compare GRPO vs Base Model on both datasets")
print("="*90 + "\n")

print("✅ Setup complete!")
print(f"📦 Base Model: {BASE_MODEL}")
print(f"📊 Training Dataset: {TRAIN_DATASET}")
print(f"📊 Eval Datasets: MBPP + HumanEval")
print(f"🔧 Backend: TRL")
print(f"💾 Output: {OUTPUT_DIR}")

"""## DAPO Model Training"""

from aligntune.core.backend_factory import create_rl_trainer

dapo_trainer = create_rl_trainer(
    model_name="meta-llama/Llama-3.2-3B-Instruct",
    dataset_name=TRAIN_DATASET,
    split="train[:1000]",
    algorithm="dapo",
    backend="trl",
    output_dir="./output/dapo_llama_code",
    max_steps=-1,
    num_epochs=3,
    batch_size=4,
    learning_rate=1e-4,
    gradient_accumulation_steps=32,
    max_prompt_length=512,
    max_completion_length=512,
    temperature=0.7,
    top_p=0.95,
    num_generations=4,
    beta=0.1,
    warmup_steps=10,
    max_grad_norm=1.0,
    use_lora=True,
    lora_r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    gradient_checkpointing=True,

    quantization={"load_in_4bit": True},
    lora_target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                         "gate_proj", "up_proj", "down_proj"],

    rewards=[
        {
            "type": "code_quality",
            "weight": 1.0,
            "params": {},
        },
    ],
    save_steps=50,
    logging_steps=10,
    loggers=["tensorboard"],
    seed=42
)

print("\n=== Starting DAPO Training ===")
print("Dynamic Adaptive Policy Optimization for Code Generation")
print("\nRewards:")
print("  1. Code Quality (weight: 0.6) - Syntax, style, efficiency checks")
print("  2. Efficiency (weight: 0.4) - Code complexity and builtin usage")
print("\nDAPO Features:")
print("  - Dynamic sampling strategy")
print("  - Adaptive policy updates")
print("  - Efficient exploration-exploitation balance\n")

dapo_results = dapo_trainer.train()

print(f"\n=== DAPO Training Completed ===")
print(f"Final Loss: {dapo_results.get('final_loss', 0.0):.4f}")
print(f"Total Steps: {dapo_results.get('total_steps', 0)}")
print(f"Training Time: {dapo_results.get('training_time', 0.0):.2f}s")
print(f"Model saved to: {dapo_results.get('model_path', 'N/A')}")

"""## Evaluation on MBPP"""

# Cell 3: Evaluate on MBPP, Compare Results (DAPO)

print("\n" + "="*70)
print("EVALUATING BASE AND DAPO MODELS ON MBPP")
print("="*70)

# Dataset configuration
eval_datasets = [
    {
        'name': 'google-research-datasets/mbpp',
        'split': 'test',
        'column_mapping': {"text": "prompt", "code": "response", "test_list": "test_cases"},
        'short_name': 'mbpp'
    }
]

all_results = {'mbpp': {}}

# Evaluate on MBPP
for dataset_config in eval_datasets:
    dataset_short = dataset_config['short_name']
    print(f"\n{'#'*70}")
    print(f"# EVALUATING ON {dataset_short.upper()}")
    print(f"{'#'*70}")

    # Evaluate Base Model
    print(f"\n[1/2] BASE MODEL")
    base_eval = run_evaluation(
        model_path=BASE_MODEL,
        dataset_name=dataset_config['name'],
        dataset_split=dataset_config['split'],
        column_mapping=dataset_config['column_mapping'],
        output_dir=OUTPUT_DIR,
        eval_name="base",
        use_lora=False
    )

    # Evaluate DAPO Model
    print(f"\n[2/2] DAPO MODEL")
    dapo_eval = run_evaluation(
        model_path="./output/dapo_llama_code",
        dataset_name=dataset_config['name'],
        dataset_split=dataset_config['split'],
        column_mapping=dataset_config['column_mapping'],
        output_dir=OUTPUT_DIR,
        eval_name="dapo",
        use_lora=True,
        base_model=BASE_MODEL
    )

    # Store results
    all_results[dataset_short] = {
        'base': base_eval,
        'dapo': dapo_eval
    }

print("\n" + "="*70)
print("✅ All evaluations complete!")
print("="*70)

"""## Comprehensive Comparison of Results"""

# ============================================================================
# COMPREHENSIVE COMPARISON
# ============================================================================

def print_dataset_comparison(dataset_name, results):
    """Print Pass@K comparison for a specific dataset"""
    print("\n" + "="*80)
    print(f"RESULTS ON {dataset_name.upper()}")
    print("="*80)

    base = results['base']
    dapo = results['dapo']

    # Extract Pass@K metrics (convert to percentages)
    base_p1 = base['pass_at_1'] * 100
    base_p2 = base['pass_at_2'] * 100
    base_p5 = base['pass_at_5'] * 100
    base_p10 = base['pass_at_10'] * 100

    dapo_p1 = dapo['pass_at_1'] * 100
    dapo_p2 = dapo['pass_at_2'] * 100
    dapo_p5 = dapo['pass_at_5'] * 100
    dapo_p10 = dapo['pass_at_10'] * 100

    # Pass@K Table
    print(f"\n{'Model':<20} {'Pass@1':<12} {'Pass@2':<12} {'Pass@5':<12} {'Pass@10':<12}")
    print("-" * 80)
    print(f"{'Base Model':<20} {base_p1:<12.2f} {base_p2:<12.2f} {base_p5:<12.2f} {base_p10:<12.2f}")
    print(f"{'DAPO (TRL)':<20} {dapo_p1:<12.2f} {dapo_p2:<12.2f} {dapo_p5:<12.2f} {dapo_p10:<12.2f}")

    # Improvements
    print(f"\n{'='*80}")
    print("IMPROVEMENTS OVER BASE MODEL")
    print(f"{'='*80}")

    print(f"\n{'Metric':<20} {'Absolute Δ':<15} {'Relative Δ (%)':<15}")
    print("-" * 80)

    for metric_name, dapo_val, base_val in [
        ('Pass@1', dapo_p1, base_p1),
        ('Pass@2', dapo_p2, base_p2),
        ('Pass@5', dapo_p5, base_p5),
        ('Pass@10', dapo_p10, base_p10)
    ]:
        abs_imp = dapo_val - base_val
        rel_imp = (abs_imp / base_val * 100) if base_val > 0 else 0
        print(f"{metric_name:<20} {abs_imp:+<15.2f} {rel_imp:+<15.2f}")

    return {
        'pass_at_1': dapo_p1 - base_p1,
        'pass_at_2': dapo_p2 - base_p2,
        'pass_at_5': dapo_p5 - base_p5,
        'pass_at_10': dapo_p10 - base_p10
    }

# Print comparison
print("\n" + "#"*80)
print("COMPARISON: BASE vs DAPO ON MBPP")
print("#"*80)

mbpp_improvements = print_dataset_comparison('MBPP', all_results['mbpp'])

# Save results
Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
results_file = Path(OUTPUT_DIR) / 'comprehensive_results_dapo.json'

with open(results_file, 'w') as f:
    json.dump(all_results, f, indent=2)