# -*- coding: utf-8 -*-
"""DrGRPO_unsloth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAFF9LAyQw0sJfxQTE_HLaF0Xl56hfsG

<center>

<div style="text-align:center;">
<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/aligntune/refs/heads/main/assets/aligntune-banner.png" width="690"></a>

<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/docs.png" width="150"></a>
<a href="https://discord.gg/dSB62Q7A"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/discord.png" width="150"></a>
</a>

<a href="https://arxiv.org/abs/2511.02802"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/lexsilogo.png" width="200"></a>
</div>

Join Discord if you need help +  <i>Star us on <a href="https://github.com/Lexsi-Labs/aligntune">Github</a> </i>

To run this, press "*Runtime*" and press "*Run all*" on a Google Colab instance!
</center>

# DrGRPO Training with Unsloth

This notebook demonstrates training a language model using Dr. GRPO (Debiased Reward-weighted Group Reward Policy Optimization) on the alpaca dataset.

## 1. Setup

Install required packages and authenticate with Hugging Face.
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Lexsi-Labs/aligntune.git
# %cd aligntune/
!pip install -e .

"""## 2. Imports"""

import os
from aligntune.core.backend_factory import create_rl_trainer
from aligntune.eval.runner import EvalConfig, run_eval

"""## 3. Shared Configuration

Define model, dataset, and preprocessing function.
"""

model_name = "Qwen/Qwen2.5-3B-Instruct"
dataset_name = "yahma/alpaca-cleaned"
output_dir = "./output/dr_grpo_qwen"

results = {
    "model": model_name,
    "dataset": dataset_name,
    "output_dir": output_dir
}

"""## 4. Train Dr. GRPO

Configure and train the model using Dr. GRPO with multiple reward signals.
"""

dr_grpo_trainer = create_rl_trainer(
    model_name=model_name,
    dataset_name=dataset_name,
    split="train[:2000]",
    column_mapping={"instruction": "prompt", "output": "response"},
    algorithm="drgrpo",
    backend="unsloth",
    output_dir=output_dir,
    num_epochs=1,
    max_steps=50,
    batch_size=16,
    learning_rate=5e-5,
    gradient_accumulation_steps=2,
    max_prompt_length=512,
    max_completion_length=512,
    temperature=0.7,
    top_p=0.9,
    num_generations=4,
    beta=0.1,
    epsilon=0.2,
    loss_type="dr_grpo",
    scale_rewards="group",
    # mask_truncated_completions=True,
    warmup_ratio=0.1,
    weight_decay=0.0,
    max_grad_norm=0.5,
    use_peft=True,
    lora_r=16,
    lora_alpha=32,
    lora_dropout=0,
    lora_target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj"
    ],
    bf16=True,
    max_seq_length=1024,
    rewards=[
        {"type": "coherence", "weight": 0.4, "params": {}},
        {"type": "sentiment", "weight": 0.3, "params": {"positive_weight": 1.0}},
        {"type": "length", "weight": 0.3, "params": {"min_length": 20, "max_length": 200}}
    ],
    save_steps=50,
    logging_steps=20,
    seed=42,
    gradient_checkpointing=True,
    group_by_length=True,
    eval_stategy = 'steps'
)

"""#### If Recompiled limit error comes increase the cache limit Session ```torch._dynamo.config.cache_size_limit```  and restart session"""

print("\n=== Starting Dr. GRPO Training ===")
print("Unbiased GRPO Variant with Debiasing Techniques")
print("\nRewards:")
print("  1. Coherence (weight: 0.4) - Logical flow and consistency")
print("  2. Sentiment (weight: 0.3) - Positive sentiment")
print("  3. Length (normalized, weight: 0.3) - Optimal length 20-200 tokens")
print("\nDr. GRPO Features:")
print("  - Debiased gradient estimates")
print("  - Group-based reward scaling")
print("  - Regularized policy updates\n")
import torch # Import torch

torch._dynamo.config.cache_size_limit = 4096 # Increase cache limit further for torch.compile
try:
    dr_grpo_results = dr_grpo_trainer.train()

    print(f"\n=== Dr. GRPO Training Completed ===")
    print(f"Final Loss: {dr_grpo_results.get('final_loss', 0.0):.4f}")
    print(f"Total Steps: {dr_grpo_results.get('total_steps', 0)}")
    print(f"Training Time: {dr_grpo_results.get('training_time', 0.0):.2f}s")
    print(f"Model saved to: {dr_grpo_results.get('model_path', 'N/A')}")

    trained_model_path = dr_grpo_results.get("model_path")
    results["training"] = dr_grpo_results

except Exception as e:
    print(f"Training failed with error: {e}")
    import traceback
    traceback.print_exc()
    trained_model_path = None

"""## 5. Evaluate Trained Model

Evaluate the trained model on the test set.
"""

print("\n" + "=" * 70)
print("STEP 2: EVALUATION — TRAINED MODEL")
print("=" * 70)

trained_config = EvalConfig(
    model_path=trained_model_path,
    output_dir=f"{output_dir}/eval_trained",
    device="cuda",
    base_model=model_name,

    task_type="text",

    dataset_name=dataset_name,
    split="test",

    max_length=512,
    temperature=0.001,
    do_sample = False,
    batch_size=8,
    max_samples=100,
    use_unsloth=True,
    use_lora=True,
    num_print_samples=0,
)

trained_results = run_eval(trained_config,dr_grpo_trainer.dataset_dict)
results["eval_trained"] = trained_results

"""## 6. Evaluate Base Model

Evaluate the base model for comparison.
"""

print("\n>>> Evaluating BASE model...")

base_config = EvalConfig(
    model_path=model_name,
    output_dir=f"{output_dir}/eval_base",
    device="cuda",

    task_type="text",
    dataset_name=dataset_name,
    split="test",

    max_length=1024,
    temperature=0.01,
    do_sample = False,
    batch_size=8,
    max_samples=100,
    num_print_samples=0,

    use_lora=False,
    use_unsloth=True,
)

base_results = run_eval(base_config,dr_grpo_trainer.dataset_dict)
results["eval_base"] = base_results

"""## 7. Comparison

Compare base and trained model performance.
"""

print("\n" + "=" * 70)
print("COMPARISON TABLE")
print("=" * 70)

# Remove the comma after the list - it was creating a tuple
metrics = ["bleu", "rouge", "perplexity"]

print(f"{'Metric':<20} | {'Base Model':<15} | {'Trained Model':<15}")
print("-" * 70)  # Match the width of the header

for metric in metrics:
    base_value = results['eval_base'].get(metric, "N/A")
    trained_value = results['eval_trained'].get(metric, "N/A")

    base_formatted = f"{base_value:.4f}" if isinstance(base_value, float) else str(base_value)
    trained_formatted = f"{trained_value:.4f}" if isinstance(trained_value, float) else str(trained_value)

    print(f"{metric:<20} | {base_formatted:<15} | {trained_formatted:<15}")

print("=" * 70)

# Define accuracy for potential future use
trained_accuracy = results['eval_trained'].get("rouge", 0.0) * 100
base_accuracy = results['eval_base'].get("rouge", 0.0) * 100

"""## 8. Save Results

Save all results to a JSON file.
"""

import json
from pathlib import Path

Path(output_dir).mkdir(parents=True, exist_ok=True)
save_path = Path(output_dir) / "comprehensive_results.json"

with open(save_path, "w") as f:
    json.dump(results, f, indent=2)

print("\n📁 Results saved to:", save_path)

