# -*- coding: utf-8 -*-
"""GRPO_code_gen_TRL_mbpp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13HYZ-EkLC3-6wxJG_1NyWXPEuN9bIeM4

<center>

<div style="text-align:center;">
<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/aligntune/refs/heads/main/assets/aligntune-banner.png" width="690"></a>

<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/docs.png" width="150"></a>
<a href="https://discord.gg/dSB62Q7A"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/discord.png" width="150"></a>
</a>

<a href="https://arxiv.org/abs/2511.02802"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/lexsilogo.png" width="200"></a>
</div>

Join Discord if you need help +  <i>Star us on <a href="https://github.com/Lexsi-Labs/aligntune">Github</a> </i>

To run this, press "*Runtime*" and press "*Run all*" on a Google Colab instance!
</center>

## 0. Environment Setup
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Lexsi-Labs/aligntune.git
# %cd aligntune/
!pip install -e .

"""## 1. Setup, Configuration, and Helper Functions"""

# Cell 1: Setup, Configuration, and Helper Functions

import gc
import json
import torch
from pathlib import Path
from aligntune.core.backend_factory import create_rl_trainer
from aligntune.eval.runner import EvalConfig, run_eval

def cleanup_memory():
    """Aggressive memory cleanup"""
    gc.collect()
    torch.cuda.empty_cache()
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    print("✓ Memory cleaned")

def run_evaluation(model_path, dataset_name, dataset_split, column_mapping,
                   output_dir, eval_name, use_lora=False, base_model=None):
    """Run evaluation on test set with Pass@K and code quality metrics."""
    dataset_short = dataset_name.split('/')[-1]
    print(f"\n>>> Evaluating {eval_name.upper()} model on {dataset_short.upper()}...")

    eval_config = EvalConfig(
        # Model & Hardware
        model_path=model_path,
        output_dir=f"{output_dir}/eval_{eval_name}_{dataset_short}",
        device="cuda",

        # Task & Metrics
        task_type="code",
        metrics=["pass_at_k"],
        k_list=[1, 2, 5, 10],

        # Dataset
        dataset_name=dataset_name,
        dataset_config=None,
        split=dataset_split,
        column_mapping=column_mapping,

        # Generation Parameters
        max_length=512,
        temperature=0.2,
        batch_size=8,
        max_samples=100,
        num_samples=10,

        # PEFT / Adapters
        use_lora=use_lora,
        base_model=base_model,
        num_print_samples=0,

    )

    results = run_eval(eval_config)


    cleanup_memory()

    return {
        'pass_at_1': results.get('pass_at_1', 0.0),
        'pass_at_2': results.get('pass_at_2', 0.0),
        'pass_at_5': results.get('pass_at_5', 0.0),
        'pass_at_10': results.get('pass_at_10', 0.0),
        'total_samples': results.get('total', 100),
        'output_dir': eval_config.output_dir
    }

# Configuration
BASE_MODEL = "Qwen/Qwen3-4B"
TRAIN_DATASET = "google-research-datasets/mbpp"
OUTPUT_DIR = "output/grpo_mbpp_comparison"

print("="*90)
print("GRPO TRAINING WITH MBPP - CODE GENERATION EVALUATION")
print("="*90)
print("\nThis pipeline will:")
print("  1. Train a GRPO model with mbpp_reward (code execution + test cases)")
print("  2. Evaluate Base Model and GRPO on MBPP and HumanEval")
print("  3. Evaluate Pass@K (k=1,2,5,10), Code Syntax, and Code Quality")
print("  4. Compare GRPO vs Base Model on both datasets")
print("="*90 + "\n")

print("✅ Setup complete!")
print(f"📦 Base Model: {BASE_MODEL}")
print(f"📊 Training Dataset: {TRAIN_DATASET}")
print(f"📊 Eval Datasets: MBPP + HumanEval")
print(f"🔧 Backend: TRL")
print(f"💾 Output: {OUTPUT_DIR}")

"""## 2. Train GRPO Model on MBPP"""

# Cell 2: Train GRPO Model on MBPP

print("\n" + "="*70)
print("TRAINING GRPO MODEL ON MBPP (TRL Backend)")
print("="*70)
print("\nUsing reward: mbpp_reward (code execution + test cases)")
print("Backend: TRL (HuggingFace Transformers Reinforcement Learning)\n")

trainer = create_rl_trainer(
    model_name=BASE_MODEL,
    dataset_name=TRAIN_DATASET,
    algorithm="grpo",
    backend="trl",  # TRL backend

    # Dataset configuration
    column_mapping={"text": "prompt", "code": "response"},
    # split="train[:100]",

    # Output
    output_dir=f"{OUTPUT_DIR}/grpo_mbpp_reward",

    # Training config
    batch_size=32,
    num_generations=4,
    loss_type="grpo",
    max_steps=100,
    num_epochs=2,
    learning_rate=1e-5,
    gradient_accumulation_steps=2,

    # Generation config
    max_prompt_length=256,
    max_completion_length=512,
    temperature=0.6,
    top_p=0.95,
    beta=0.01,

    # LoRA config
    use_peft=True,
    lora_r=32,
    lora_alpha=64,
    lora_dropout=0.01,
    lora_target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                         "gate_proj", "up_proj", "down_proj"],

    rewards=[
        {
            "type": "code_quality",
            "weight": 1.0,
            "params": {},
        },
    ],

    # Other settings
    bf16=True,
    max_seq_length=1024,
    save_steps=100,
    save_total_limit=3,
    logging_steps=10,
    seed=42,
)

print("🚀 Starting GRPO training on MBPP...\n")
training_results = trainer.train()

print("\n" + "="*70)
print("✅ GRPO TRAINING COMPLETE!")
print("="*70)
print(f"Model saved to: {OUTPUT_DIR}/grpo_mbpp_reward")
print(f"Final loss: {training_results.get('final_loss', 'N/A')}")
print(f"Total steps: {training_results.get('total_steps', 'N/A')}")

# Store training info
grpo_model_path = f"{OUTPUT_DIR}/grpo_mbpp_reward"
training_info = {
    'algorithm': 'grpo',
    'reward_type': 'mbpp_reward',
    'final_loss': training_results.get('final_loss', 0.0),
    'total_steps': training_results.get('total_steps', 0),
    'model_path': grpo_model_path
}

cleanup_memory()

"""## 3. Evaluate Base and GRPO Models on MBPP"""

# Cell 3: Evaluate on MBPP, Compare Results
print("\n" + "="*70)
print("EVALUATING BASE AND GRPO MODELS ON MBPP")
print("="*70)

# Dataset configuration - MBPP only
eval_dataset = {
    'name': 'google-research-datasets/mbpp',
    'split': 'test',
    'column_mapping': {"text": "prompt", "code": "response", "test_list": "test_cases"},
    'short_name': 'mbpp'
}

all_results = {'mbpp': {}}

# Evaluate on MBPP
print(f"\n{'#'*70}")
print(f"# EVALUATING ON MBPP")
print(f"{'#'*70}")

# Evaluate Base Model
print(f"\n[1/2] BASE MODEL")
base_eval = run_evaluation(
    model_path=BASE_MODEL,
    dataset_name=eval_dataset['name'],
    dataset_split=eval_dataset['split'],
    column_mapping=eval_dataset['column_mapping'],
    output_dir=OUTPUT_DIR,
    eval_name="base",
    use_lora=False
)

# Evaluate GRPO Model
print(f"\n[2/2] GRPO MODEL")
grpo_eval = run_evaluation(
    model_path=grpo_model_path,
    dataset_name=eval_dataset['name'],
    dataset_split=eval_dataset['split'],
    column_mapping=eval_dataset['column_mapping'],
    output_dir=OUTPUT_DIR,
    eval_name="grpo",
    use_lora=True,
    base_model=BASE_MODEL
)

# Store results
all_results['mbpp'] = {
    'base': base_eval,
    'grpo': grpo_eval
}



print("\n" + "="*70)
print("✅ Evaluation complete on MBPP!")
print("="*70)

"""## 4. Comprehensive Comparison and Results Display"""

# ============================================================================
# COMPREHENSIVE COMPARISON
# ============================================================================

print("\n" + "#"*100)
print("COMPREHENSIVE COMPARISON: BASE vs GRPO ON MBPP")
print("#"*100)

print("\n" + "="*100)
print("RESULTS ON MBPP")
print("="*100)

base = all_results['mbpp']['base']
grpo = all_results['mbpp']['grpo']

# Extract metrics (convert to percentages)
base_p1 = base['pass_at_1'] * 100
base_p2 = base['pass_at_2'] * 100
base_p5 = base['pass_at_5'] * 100
base_p10 = base['pass_at_10'] * 100

grpo_p1 = grpo['pass_at_1'] * 100
grpo_p2 = grpo['pass_at_2'] * 100
grpo_p5 = grpo['pass_at_5'] * 100
grpo_p10 = grpo['pass_at_10'] * 100


# Table 1: Pass@K Metrics
print(f"\n{'Model':<20} {'Pass@1':<12} {'Pass@2':<12} {'Pass@5':<12} {'Pass@10':<12}")
print("-" * 100)
print(f"{'Base Model':<20} {base_p1:<12.2f} {base_p2:<12.2f} {base_p5:<12.2f} {base_p10:<12.2f}")
print(f"{'GRPO (TRL)':<20} {grpo_p1:<12.2f} {grpo_p2:<12.2f} {grpo_p5:<12.2f} {grpo_p10:<12.2f}")



# Improvements
print(f"\n{'='*100}")
print("IMPROVEMENTS OVER BASE MODEL")
print(f"{'='*100}")
print(f"\n{'Metric':<20} {'Absolute Δ':<15} {'Relative Δ (%)':<15}")
print("-" * 100)

metrics_comparison = [
    ('Pass@1', grpo_p1 - base_p1, base_p1),
    ('Pass@2', grpo_p2 - base_p2, base_p2),
    ('Pass@5', grpo_p5 - base_p5, base_p5),
    ('Pass@10', grpo_p10 - base_p10, base_p10),
]

for metric_name, abs_imp, base_val in metrics_comparison:
    rel_imp = (abs_imp / base_val * 100) if base_val > 0 else 0
    print(f"{metric_name:<20} {abs_imp:+<15.2f} {rel_imp:+<15.2f}")

# Performance Summary
print(f"\n{'='*100}")
print(f"PERFORMANCE SUMMARY - MBPP")
print(f"{'='*100}")

if grpo_p1 > base_p1:
    print(f"\n✅ GRPO improves Pass@1 by {grpo_p1 - base_p1:+.2f}%")
else:
    print(f"\n⚠️ GRPO decreases Pass@1 by {abs(grpo_p1 - base_p1):.2f}%")

if grpo_p10 > base_p10:
    print(f"✅ GRPO improves Pass@10 by {grpo_p10 - base_p10:+.2f}%")
else:
    print(f"⚠️ GRPO decreases Pass@10 by {abs(grpo_p10 - base_p10):.2f}%")


# Save comprehensive results
Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
results_file = Path(OUTPUT_DIR) / 'comprehensive_results.json'
with open(results_file, 'w') as f:
    json.dump(all_results, f, indent=2)

