# -*- coding: utf-8 -*-
"""GSPO_Generic_Demo_Unsloth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120FjMEAZRXUoOMRsWHCn5tmpGfLTAY4g

<center>

<div style="text-align:center;">
<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/aligntune/refs/heads/docs/assets/banner_aligntune.png" width="690"></a>

<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/docs.png" width="150"></a>
<a href="https://discord.gg/dSB62Q7A"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/discord.png" width="150"></a>
</a>

<a href="https://arxiv.org/abs/2511.02802"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/lexsilogo.png" width="200"></a>
</div>

Join Discord if you need help +  <i>Star us on <a href="https://github.com/Lexsi-Labs/aligntune">Github</a> </i>

To run this, press "*Runtime*" and press "*Run all*" on a Google Colab instance!
</center>

### 1. Setup and Installation
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Lexsi-Labs/aligntune.git
# %cd aligntune/
!pip install -e .

"""### 2. Import Libraries"""

import os
import torch
from aligntune.core.backend_factory import create_rl_trainer
from aligntune.eval.runner import EvalConfig, run_eval
from datasets import load_dataset
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import time

"""## 2. GSPO Training with Sequential Group Rewards

**Parameters from:** `src/aligntune/backends/unsloth/rl/gspo/gspo.py`
- **LoRA config** (lines 107-111): r=16, alpha=16, dropout=0
- **Default rewards** (lines 145-148): length, coherence, safety
- **Training params** (lines 364-437):
  - batch_size: 4
  - learning_rate: 5e-5
  - beta (KL coef): 0.1
  - temperature: 0.7
  - num_generations: 4
  - warmup_ratio: 0.1
  - max_grad_norm: 0.5
"""

gspo_trainer = create_rl_trainer(
    model_name="Qwen/Qwen3-1.7B",
    dataset_name="CyberNative/Code_Vulnerability_Security_DPO",
    split="train[:2000]",
    column_mapping={"question": "prompt", "chosen": "response"},
    algorithm="gspo",
    backend="unsloth",
    output_dir="./output/gspo_qwen3_code_dpo",
    num_epochs=2,
    max_steps=100,
    batch_size=4,
    learning_rate=1e-5,
    gradient_accumulation_steps=4,
    max_prompt_length=512,
    max_completion_length=512,
    temperature=0.7,
    top_p=0.95,
    num_generations=4,
    beta=0.1,
    warmup_ratio=0.1,
    max_grad_norm=0.5,
    use_peft=True,
    lora_r=16,
    lora_alpha=32,
    lora_dropout=0,
    lora_target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bf16=True,
    max_seq_length=1024,
    rewards=[
    {"type": "helpfulness", "weight": 0.5, "params": {}},
    {"type": "honesty", "weight": 0.3, "params": {}},
    {"type": "instruction_following", "weight": 0.2, "params": {}}
],
    save_steps=100,
    logging_steps=10,
    seed=42,
    gradient_checkpointing=True,
    group_by_length=True,
)

print("\n=== Starting GSPO Training ===")
print("Sequential Group Rewards:")
print("  1. Coherence (weight: 0.4)")
print("  2. Safety (weight: 0.4)")
print("  3. Length (weight: 0.2)")
print("\nNote: Using GRPOTrainer as GSPO approximation (TRL limitation)\n")

gspo_results = gspo_trainer.train()

print(f"\n=== GSPO Training Completed ===")
print(f"Final Loss: {gspo_results.get('final_loss', 0.0):.4f}")
print(f"Total Steps: {gspo_results.get('total_steps', 0)}")
print(f"Training Time: {gspo_results.get('training_time', 0.0):.2f}s")
print(f"Model saved to: {gspo_results.get('model_path', 'N/A')}")

"""## 4. GSPO Model Evaluation"""

# Add 'chosen' column to all splits by copying from 'response'
gspo_trainer.dataset_dict = gspo_trainer.dataset_dict.map(
    lambda example: {'chosen': example['response']},
    desc="Adding chosen column"
)

model_name = "Qwen/Qwen3-1.7B"

base_eval_config = EvalConfig(
    model_path=model_name,
    output_dir="./output/eval_base_qwen3",
    device="cuda",

    # processing_fn=preprocess_ultrafeedback_binarized,

    data_task_type="dpo",
    task_type="text",
    metrics=["kl_divergence", "win_rate"],
    dataset_name="CyberNative/Code_Vulnerability_Security_DPO",
    split="train_prefs",

    max_length=512,
    temperature=0.1,
    batch_size=8,
    max_samples=100,

    use_lora=False,
    use_unsloth=True
)

print("\n=== Evaluating Base Model ===")
base_results = run_eval(base_eval_config,gspo_trainer.dataset_dict)

from aligntune.eval.runner import EvalConfig, run_eval

# GSPO Model Evaluation with EvalConfig
gspo_eval_config = EvalConfig(
    model_path="./output/gspo_qwen3_code_dpo",
    output_dir="./output/eval_gspo_qwen3",
    dataset_name="CyberNative/Code_Vulnerability_Security_DPO",
    batch_size=4,
    max_samples=100,
    max_length=512,
    temperature=0.1,
    use_lora=True,
    base_model="Qwen/Qwen3-1.7B",
    device="cuda",

    trust_remote_code=True,

    data_task_type="dpo",
    use_unsloth=True,
    task_type="text",
    reference_model_path = "Qwen/Qwen3-1.7B",
    metrics=["kl_divergence", "win_rate"],
    num_print_samples=0,

)

print("\n=== Evaluating GSPO Model ===")
gspo_eval_results = run_eval(gspo_eval_config,gspo_trainer.dataset_dict)

"""## 5. Results Comparison"""

# Metrics extraction for preference learning evaluation
comparison_data = {
    "Model": ["Base (Qwen3)", "GSPO Trained"],
    "KL Divergence": [
        base_results.get('kl_divergence', 0.0),
        gspo_eval_results.get('kl_divergence', 0.0)
    ],
    "Win Rate": [
        base_results.get('win_rate', 0.0),
        gspo_eval_results.get('win_rate', 0.0)
    ],
}
comparison_df = pd.DataFrame(comparison_data)
print("\n" + "="*70)
print("FINAL COMPARISON - Code_Vulnerability_Security_DPO (100 samples)")
print("="*70)
print(comparison_df.to_string(index=False))
print("="*70)

# KL Divergence Analysis (lower is better - less deviation from base)
if comparison_df.loc[1, "KL Divergence"] > 0:
    print(f"\n📊 KL Divergence (Policy Drift):")
    print(f"   Base → GSPO: {comparison_df.loc[1, 'KL Divergence']:.4f}")
    print(f"   {'✓ Low drift' if comparison_df.loc[1, 'KL Divergence'] < 0.5 else '⚠ High drift - may lose base model capabilities'}")

# Win Rate Analysis (higher is better)
if comparison_df.loc[1, "Win Rate"] > 0:
    win_rate_improvement = (comparison_df.loc[1, "Win Rate"] - comparison_df.loc[0, "Win Rate"]) * 100
    print(f"\n🏆 Win Rate (Preference Accuracy):")
    print(f"   Improvement: {win_rate_improvement:+.2f}%")
    print(f"   GSPO Model: {comparison_df.loc[1, 'Win Rate']:.2%}")
    print(f"   {'✓ Strong preference learning' if comparison_df.loc[1, 'Win Rate'] > 0.55 else '⚠ Weak preference signal'}")

