# -*- coding: utf-8 -*-
"""GSPO_TRL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k9UjIqdNClnGADeJzfVUeE6UVgjzc5wV

<center>

<div style="text-align:center;">
<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/aligntune/refs/heads/main/assets/aligntune-banner.png" width="690"></a>

<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/docs.png" width="150"></a>
<a href="https://discord.gg/dSB62Q7A"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/discord.png" width="150"></a>
</a>

<a href="https://arxiv.org/abs/2511.02802"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/lexsilogo.png" width="200"></a>
</div>

Join Discord if you need help +  <i>Star us on <a href="https://github.com/Lexsi-Labs/aligntune">Github</a> </i>

To run this, press "*Runtime*" and press "*Run all*" on a Google Colab instance!
</center>

### 1. Setup and Installation
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Lexsi-Labs/aligntune.git
# %cd aligntune/
!pip install -e .

"""### 2. Import Libraries"""

import torch
from aligntune.core.backend_factory import create_rl_trainer
from aligntune.eval.runner import EvalConfig, run_eval
from datasets import load_dataset
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import time

"""### 3. HuggingFace Login and Model Definition"""

model_name = "meta-llama/Llama-3.2-3B-Instruct"

"""### 4. GSPO Model Training"""

gspo_trainer = create_rl_trainer(
    model_name="meta-llama/Llama-3.2-3B-Instruct",
    dataset_name="HuggingFaceH4/ultrachat_200k",
    split="train_gen[:2000]",
    algorithm="gspo",
    backend="trl",
    output_dir="./output/gspo_llama_ultrafeedback",
    num_epochs=2,
    max_steps=100,
    batch_size=32,
    learning_rate=5e-5,
    gradient_accumulation_steps=2,
    max_prompt_length=512,
    max_completion_length=512,
    temperature=0.7,
    top_p=0.95,
    num_generations=4,
    beta=0.1,
    warmup_ratio=0.1,
    max_grad_norm=0.5,
    use_peft=True,

    # Quantization (4-bit for memory efficiency)
    quantization={"load_in_4bit": True, "bnb_4bit_compute_dtype": "bfloat16"},

    lora_r=32,
    lora_alpha=64,
    lora_dropout=0.1,
    lora_target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bf16=True,
    max_seq_length=1024,

    rewards=[
    {"type": "helpfulness", "weight": 0.5, "params": {}},
    {"type": "honesty", "weight": 0.3, "params": {}},
    {"type": "instruction_following", "weight": 0.2, "params": {}}
],
    save_steps=100,
    logging_steps=10,
    seed=42,
    # gradient_checkpointing=True,
    group_by_length=True,
)

print("\n=== Starting GSPO Training ===")
print("Sequential Group Rewards:")
print("  1. Coherence (weight: 0.4)")
print("  2. Safety (weight: 0.4)")
print("  3. Length (weight: 0.2)")
print("\nNote: Using GRPOTrainer as GSPO approximation (TRL limitation)\n")

gspo_trainer.train()

print(f"\n=== GSPO Training Completed ===")

"""### 5. Base Model Evaluation"""

base_eval_config = EvalConfig(
    model_path=model_name,
    output_dir="./output/eval_base_llama",
    device="cuda",
    data_task_type="dpo",
    dataset_name="HuggingFaceH4/ultrachat_200k",
    task_type="text",
    metrics=["kl_divergence", "win_rate", "bleu"],
    split="test_gen",
    reference_model_path = "meta-llama/Llama-3.2-1B-Instruct",

    max_length=512,
    temperature=0.1,
    batch_size=8,
    max_samples=100,

    use_lora=False,
    use_unsloth=False
)

print("\n=== Evaluating Base Model ===")
base_results = run_eval(base_eval_config)

"""### 6. GSPO Tuned Model Evaluation"""

from aligntune.eval.runner import EvalConfig, run_eval

# GSPO Model Evaluation with EvalConfig
gspo_eval_config = EvalConfig(
    model_path="./output/gspo_llama_ultrafeedback",
    output_dir="./output/eval_gspo_qwen3",
    dataset_name="HuggingFaceH4/ultrachat_200k",
    split="test_gen[:1%]",  # 100 samples for evaluation
    batch_size=4,
    max_samples=100,
    max_length=512,
    temperature=0.1,
    use_lora=True,
    reference_model_path = "meta-llama/Llama-3.2-1B-Instruct",
    base_model="meta-llama/Llama-3.2-3B-Instruct",
    device="cuda",

    trust_remote_code=True,

    data_task_type="dpo",
    task_type="text",
    metrics=["kl_divergence", "win_rate", "bleu"],
)

print("\n=== Evaluating GSPO Model ===")
gspo_eval_results = run_eval(gspo_eval_config)

"""### 7. Evaluation Results Comparison"""

# Metrics extraction for preference learning evaluation
comparison_data = {
    "Model": ["Base (Qwen3)", "GSPO Trained"],
    "KL Divergence": [
        base_results.get('kl_divergence', 0.0),
        gspo_eval_results.get('kl_divergence', 0.0)
    ],
    "Win Rate": [
        base_results.get('win_rate', 0.0),
        gspo_eval_results.get('win_rate', 0.0)
    ],
    "BLEU Score": [
        base_results.get('bleu', 0.0),
        gspo_eval_results.get('bleu', 0.0)
    ],
}

comparison_df = pd.DataFrame(comparison_data)

print("\n" + "="*70)
print("FINAL COMPARISON - Ultrafeedback Evaluation (100 samples)")
print("="*70)
print(comparison_df.to_string(index=False))
print("="*70)

# KL Divergence Analysis (lower is better - less deviation from base)
if comparison_df.loc[1, "KL Divergence"] > 0:
    print(f"\n📊 KL Divergence (Policy Drift):")
    print(f"   Base → GSPO: {comparison_df.loc[1, 'KL Divergence']:.4f}")
    print(f"   {'✓ Low drift' if comparison_df.loc[1, 'KL Divergence'] < 0.5 else '⚠ High drift - may lose base model capabilities'}")

# Win Rate Analysis (higher is better)
if comparison_df.loc[1, "Win Rate"] > 0:
    win_rate_improvement = (comparison_df.loc[1, "Win Rate"] - comparison_df.loc[0, "Win Rate"]) * 100
    print(f"\n🏆 Win Rate (Preference Accuracy):")
    print(f"   Improvement: {win_rate_improvement:+.2f}%")
    print(f"   GSPO Model: {comparison_df.loc[1, 'Win Rate']:.2%}")
    print(f"   {'✓ Strong preference learning' if comparison_df.loc[1, 'Win Rate'] > 0.55 else '⚠ Weak preference signal'}")

# BLEU Score Analysis (higher is better for generation quality)
if comparison_df.loc[1, "BLEU Score"] > 0:
    bleu_change = ((comparison_df.loc[1, "BLEU Score"] - comparison_df.loc[0, "BLEU Score"]) / max(comparison_df.loc[0, "BLEU Score"], 0.001)) * 100
    print(f"\n📝 BLEU Score (Generation Quality):")
    print(f"   Change: {bleu_change:+.2f}%")
    print(f"   GSPO Model: {comparison_df.loc[1, 'BLEU Score']:.4f}")

