# -*- coding: utf-8 -*-
"""retail_banking_SFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnFvEWZ6PDqrDAyWznCdOA9oNn8aqN2v

<center>

<div style="text-align:center;">
<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/aligntune/refs/heads/docs/assets/banner_aligntune.png" width="690"></a>

<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/docs.png" width="150"></a>
<a href="https://discord.gg/dSB62Q7A"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/discord.png" width="150"></a>
</a>

<a href="https://arxiv.org/abs/2511.02802"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/lexsilogo.png" width="200"></a>
</div>

Join Discord if you need help +  <i>Star us on <a href="https://github.com/Lexsi-Labs/aligntune">Github</a> </i>

To run this, press "*Runtime*" and press "*Run all*" on a Google Colab instance!
</center>

# Setup
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Lexsi-Labs/aligntune.git
# %cd aligntune/
!pip install -e .

"""# Instruction Following Fine-tuning & Evaluation Script

1. Fine-tunes Qwen3-4B-Instruct on retail banking chatbot dataset.
2. Automatically evaluates the model on the test split after training.

## Imports
"""

import os
import sys
import json
import torch
import gc
from pathlib import Path
import traceback

from aligntune.core.backend_factory import create_sft_trainer
from aligntune.eval.runner import EvalConfig, run_eval

"""## Configuration"""

# Model and Dataset
MODEL_NAME = "Qwen/Qwen3-4B-Instruct-2507"
TOKENIZER_NAME = "Qwen/Qwen3-4B-Instruct-2507"
DATASET_NAME = "sohamb37lexsi/bitext-retail-banking-llm-chatbot-splits"
OUTPUT_DIR = "./retail_banking_model"
EVAL_OUTPUT_DIR = "./results/retail_banking"

# Training Hyperparameters
NUM_EPOCHS = 50
MAX_STEPS = 500
BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 2
LEARNING_RATE = 2e-4
WARMUP_RATIO = 0.1
MAX_SEQ_LENGTH = 1512
MAX_SAMPLES = None

# LoRA Configuration
LORA_R = 6
LORA_ALPHA = 8
LORA_DROPOUT = 0.05
LORA_TARGET_MODULES = "all-linear"

# Quantization (4-bit NF4)
QUANTIZATION = {
    "load_in_4bit": True,
    "bnb_4bit_use_double_quant": True,
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_compute_dtype": "bfloat16",
}

# Precision Settings
BF16 = True
TF32 = True

# Flash Attention
USE_FLASH_ATTENTION = True

# System Prompt
SYSTEM_PROMPT = (
    "You are Qwen. You are a helpful assistant specialized "
    "in retail banking and customer support. Provide accurate, professional, and "
    "courteous assistance to customers regarding their financial inquiries, investment "
    "questions, and retail banking needs."
)

# Dataset split for training
DATASET_SPLIT = "train"

"""## Utility Functions"""

def cleanup_memory():
    """Clear GPU memory and cache."""
    gc.collect()
    torch.cuda.empty_cache()
    if torch.cuda.is_available():
        torch.cuda.synchronize()

def print_gpu_utilization():
    """Print current GPU memory usage."""
    if torch.cuda.is_available():
        print(f"\nGPU Memory Usage:")
        for i in range(torch.cuda.device_count()):
            allocated = torch.cuda.memory_allocated(i) / 1024**3
            reserved = torch.cuda.memory_reserved(i) / 1024**3
            print(f"  GPU {i}: {allocated:.2f}GB allocated, {reserved:.2f}GB reserved")

def save_training_config(output_dir: str):
    """Save training configuration to JSON file."""
    config = {
        "model_name": MODEL_NAME,
        "dataset_name": DATASET_NAME,
        "lora_config": {
            "r": LORA_R,
            "alpha": LORA_ALPHA,
            "target_modules": LORA_TARGET_MODULES,
        },
        "system_prompt": SYSTEM_PROMPT
    }

    config_path = Path(output_dir) / "training_config.json"
    config_path.parent.mkdir(parents=True, exist_ok=True)

    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)

"""## Training Function"""

def run_training():
    """Executes the SFT training loop."""
    results = {}

    print("\n" + "=" * 80)
    print("STARTING SFT TRAINING")
    print("=" * 80)

    # Create output directory and save config
    Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
    save_training_config(OUTPUT_DIR)
    print_gpu_utilization()

    try:
        print("\n🚀 Creating SFT trainer...")

        trainer = create_sft_trainer(
            model_name=MODEL_NAME,
            dataset_name=DATASET_NAME,
            backend="trl",
            output_dir=OUTPUT_DIR,
            task_type="instruction_following",

            max_steps=MAX_STEPS,
            epochs=NUM_EPOCHS,

            batch_size=BATCH_SIZE,
            gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,

            learning_rate=LEARNING_RATE,
            warmup_ratio=WARMUP_RATIO,
            lr_scheduler_type="constant",
            max_grad_norm=0.3,
            optim="paged_adamw_8bit",

            max_seq_length=MAX_SEQ_LENGTH,
            max_samples=MAX_SAMPLES,
            dataset_text_field="messages",
            split=DATASET_SPLIT,

            use_peft=True,
            lora_r=LORA_R,
            lora_alpha=LORA_ALPHA,
            lora_dropout=LORA_DROPOUT,
            lora_target_modules=LORA_TARGET_MODULES,

            quantization=QUANTIZATION,
            bf16=BF16,
            tf32=TF32,
            gradient_checkpointing=True,

            trust_remote_code=True,
            save_strategy="epoch",
            save_total_limit=3,
            logging_steps=5,
            report_to="tensorboard",
            seed=42,
        )

        print("✅ Trainer created successfully!")

        # Start training
        print("\n🏃 TRAINING IN PROGRESS...")
        training_results = trainer.train()

        # Extract results
        if isinstance(training_results, dict):
            final_loss = training_results.get("train_loss", 0.0)
        else:
            final_loss = getattr(training_results, "training_loss", 0.0)

        print(f"\n📈 Final Training Loss: {final_loss:.4f}")
        print(f"💾 Model saved to: {OUTPUT_DIR}")

        results["status"] = "success"
        return results

    except Exception as e:
        print(f"\n❌ TRAINING FAILED: {e}")
        traceback.print_exc()
        return {"status": "failed", "error": str(e)}

    finally:
        print("\n🧹 Cleaning up training memory...")
        cleanup_memory()

"""## Evaluation Function"""

def run_evaluation():
    """Executes the evaluation loop on the trained model."""
    print("\n" + "=" * 80)
    print("STARTING EVALUATION")
    print("=" * 80)

    try:
        custom_config = EvalConfig(
            # Point to the directory where we just saved the trained model
            model_path=OUTPUT_DIR,
            output_dir=EVAL_OUTPUT_DIR,

            # --- Data ---
            data_task_type="sft",
            dataset_name=DATASET_NAME,
            system_prompt=SYSTEM_PROMPT,

            # --- Splitting Control ---
            seed=999,
            split="test",  # Evaluating on test split

            # --- Hardware ---
            device="cuda:0",
            batch_size=16, # Higher batch size for inference

            # --- Metrics ---
            metrics=["bleu", "rouge"],
        )

        print(f"📊 Evaluating model from: {OUTPUT_DIR}")
        print(f"📂 Evaluation results will be saved to: {EVAL_OUTPUT_DIR}")

        results = run_eval(custom_config)

        print("\n✅ Evaluation Results:")
        print(json.dumps(results, indent=2))
        return results

    except Exception as e:
        print(f"\n❌ EVALUATION FAILED: {e}")
        traceback.print_exc()
        return None

"""## Run Training"""

print("\n" + "=" * 80)
print("RETAIL BANKING CHATBOT - TRAINING & EVALUATION PIPELINE")
print("=" * 80)

train_results = run_training()

"""## Run Evaluation"""

if train_results.get("status") == "success":
    eval_results = run_evaluation()

    print("\n" + "=" * 80)
    print("PIPELINE COMPLETED")
    print("=" * 80)
    print("✅ Training: Success")
    print(f"✅ Evaluation: {'Success' if eval_results else 'Failed'}")
else:
    print("\n❌ Pipeline stopped due to training failure.")

"""# LM Eval

## Base ZeroShot
"""

!lm_eval \
  --model hf \
  --model_args pretrained=Qwen/Qwen3-4B-Instruct-2507 \
  --tasks retail_banking \
  --include_path content/aligntune/examples/custom_tasks \
  --device cuda \
  --batch_size 16 \
  --output_path ./lm_eval_retail_banking_base_0shot \
  --log_samples \
  --gen_kwargs max_gen_toks=1024,temperature=0.0

"""## SFT ZeroShot"""

!lm_eval \
  --model hf \
  --model_args pretrained=Qwen/Qwen3-4B-Instruct-2507,peft="./retail_banking_model" \ # use your own saved lora adapters
  --tasks retail_banking \
  --include_path content/aligntune/examples/custom_tasks \
  --device cuda \
  --batch_size 16 \
  --output_path ./lm_eval_retail_banking_sft_0shot \
  --log_samples \
  --gen_kwargs max_gen_toks=1024,temperature=0.0

"""## Base FewShot"""

!lm_eval \
  --model hf \
  --model_args pretrained=Qwen/Qwen3-4B-Instruct-2507 \
  --tasks retail_banking_fewshot \
  --include_path content/aligntune/examples/custom_tasks \
  --device cuda \
  --batch_size 16 \
  --output_path ./lm_eval_retail_banking_base_fewshot \
  --log_samples \
  --gen_kwargs max_gen_toks=1024,temperature=0.0

"""## SFT FewShot"""

!lm_eval \
  --model hf \
  --model_args pretrained=Qwen/Qwen3-4B-Instruct-2507,peft="./retail_banking_model" \ # use your own saved lora adapters
  --tasks retail_banking_fewshot \
  --include_path content/aligntune/examples/custom_tasks \
  --device cuda \
  --batch_size 16 \
  --output_path ./lm_eval_retail_banking_sft_fewshot \
  --log_samples \
  --gen_kwargs max_gen_toks=1024,temperature=0.0