# -*- coding: utf-8 -*-
"""UNSLOTH_PPO_ultrachat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4fdtO4DhBNwjOYhuaGmvIrBU_lc159H

<center>

<div style="text-align:center;">
<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/aligntune/refs/heads/main/assets/aligntune-banner.png" width="690"></a>

<a href="https://aligntune.lexsi.ai/"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/docs.png" width="150"></a>
<a href="https://discord.gg/dSB62Q7A"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/discord.png" width="150"></a>
</a>

<a href="https://arxiv.org/abs/2511.02802"><img src="https://raw.githubusercontent.com/Lexsi-Labs/TabTune/refs/heads/docs/assets/lexsilogo.png" width="200"></a>
</div>

Join Discord if you need help +  <i>Star us on <a href="https://github.com/Lexsi-Labs/aligntune">Github</a> </i>

To run this, press "*Runtime*" and press "*Run all*" on a Google Colab instance!
</center>
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/Lexsi-Labs/aligntune.git
# %cd aligntune/
!pip install -e .

# Import required libraries

import os
import random
import numpy as np
import torch

def set_seed(seed=42):
    # Python's built-in random
    random.seed(seed)

    # Numpy
    np.random.seed(seed)

    # PyTorch
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)  # for multi-GPU

    # PyTorch backends
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    # Environment variable (for some ops)
    os.environ['PYTHONHASHSEED'] = str(seed)

# Call before everything else
set_seed(42)
import sys
import json
from pathlib import Path
from aligntune.eval.runner import EvalConfig, run_eval
from aligntune.core.backend_factory import create_rl_trainer

# Configuration
MODEL_NAME = "Qwen/Qwen2.5-0.5B-Instruct"
DATASET = "HuggingFaceH4/ultrachat_200k"
OUTPUT_DIR = "./output/ppo_summarization_custom_rewards"
import gc
def cleanup_memory():
    """Clear GPU memory and cache"""
    gc.collect()
    torch.cuda.empty_cache()
    if torch.cuda.is_available():
        torch.cuda.synchronize()
    print("✓ Memory cleaned")
def run_evaluation(model_path, output_dir, eval_name, use_lora=False, base_model=None):
    """Evaluate model on dataset with text generation metrics"""
    print(f"\n>>> Evaluating {eval_name.upper()} model...")

    eval_config = EvalConfig(
        model_path=model_path,
        output_dir=f"{output_dir}/eval_{eval_name}",
        device="cuda",
        task_type="text",
        dataset_name=DATASET,
        split="test_gen",
        column_mapping={
            "prompt": "prompt",
            "label": "response"
        },
        max_length=512,
        temperature=0.1,
        batch_size=8,
        max_samples=100,
        use_lora=use_lora,
        base_model=base_model,
        use_unsloth=True,
        num_print_samples=0,
    )

    try:
        results = run_eval(eval_config)

        summary = {
            'perplexity': results.get('perplexity', 0.0),
            'rouge_l': results.get('rouge_l', results.get('rouge', 0.0)),
            'bleu': results.get('bleu', 0.0),
            'total_samples': results.get('total', 50)
        }

        print(f"✅ Perplexity: {summary['perplexity']:.4f}, "
              f"ROUGE-L: {summary['rouge_l']:.4f}, BLEU: {summary['bleu']:.4f}")

        return summary

    except Exception as e:
        print(f"❌ Evaluation failed: {e}")
        import traceback
        traceback.print_exc()
        return None
    finally:
        cleanup_memory()

print("\n" + "="*70)
print("TRAINING PPO WITH CUSTOM REWARD FUNCTIONS")
print("="*70)

print("\n🎯 PPO Configuration:")
print("   Algorithm: Proximal Policy Optimization")
print("   Reward Strategy: Custom reward functions (NO reward model)")
print("   Reward Functions: ROUGE + Factuality + Coherence + Length")
print("   Backend: Unsloth (2-5x faster)\n")
OUTPUT_DIR = "./output/ppo_summarization_custom_rewards"
ppo_output_dir = f"{OUTPUT_DIR}/ppo_custom_rewards"

ppo_trainer = create_rl_trainer(
    model_name=MODEL_NAME,
    dataset_name=DATASET,
    algorithm="ppo",
    backend="unsloth",

    # Dataset configuration
    split="train_gen[:1000]",  # Use 1000 samples for training

    # Output
    output_dir=ppo_output_dir,

    # Training configuration
    num_epochs=1,
    batch_size=4,
    mini_batch_size=4,
    learning_rate=1e-5,
    gradient_accumulation_steps=4,
    gradient_checkpointing=False,

    # PPO-specific hyperparameters
    kl_coef=0.1,           # KL divergence coefficient
    cliprange=0.2,         # PPO clip range
    vf_coef=0.1,           # Value function coefficient
    num_ppo_epochs=4,      # PPO epochs per batch

    # Generation configuration
    response_length=128,
    temperature=0.7,
    max_seq_length=512,
    max_prompt_length=384,  # max_prompt_length + response_length = max_seq_length

    # LoRA configuration
    use_lora=True,
    lora_r=64,
    lora_alpha=64,
    lora_dropout=0.1,
    lora_target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                         "gate_proj", "up_proj", "down_proj"],

    # Quantization for memory efficiency
    quantization={"load_in_4bit": True},

    # CRITICAL: Custom reward functions only (NO reward model)
    rewards=[
        {
            "type": "rouge",
            "weight": 0.3,
            "params": {
                "rouge_type": "rougeL"  # Use ROUGE-L for summary quality
            }
        },
        {
            "type": "factuality",
            "weight": 0.3,
            "params": {
                "check_consistency": True
            }
        },
        {
            "type": "coherence",
            "weight": 0.2,
            "params": {}
        },
        {
            "type": "length",
            "weight": 0.2,
            "params": {
                "min_length": 50,
                "max_length": 150,
                "target_length": 100
            }
        }
    ],

    # NO reward model - only custom reward functions
    # reward_model_name=None,  # Explicitly no reward model
    # reward_value_model=None,

    # Logging
    loggers=["tensorboard"],
    save_steps=100,
    logging_steps=10,
    seed=42,
)

print("✅ PPO Trainer created with custom reward functions")
print("\n🚀 Starting PPO training...\n")

training_results = ppo_trainer.train()

print("\n" + "="*70)
print("✅ PPO TRAINING COMPLETED!")
print("="*70)
print(f"Model saved to: {training_results.get('model_path', ppo_output_dir)}")
print(f"Final loss: {training_results.get('final_loss', 'N/A')}")
print(f"Training time: {training_results.get('training_time', 0):.2f}s")
print(f"Total steps: {training_results.get('total_steps', 'N/A')}")

# Store training info
training_info = {
    'final_loss': training_results.get('final_loss', 0.0),
    'training_time': training_results.get('training_time', 0),
    'total_steps': training_results.get('total_steps', 0),
    'model_path': training_results.get('model_path', ppo_output_dir)
}

cleanup_memory()

# Evaluate base model
print("[1/2] Evaluating Base Model...")
base_results = run_evaluation(
    model_path=MODEL_NAME,
    output_dir=OUTPUT_DIR,
    eval_name="base",
    use_lora=False
)

# Evaluate PPO model
ppo_output_dir = f"{OUTPUT_DIR}/ppo_custom_rewards"
print("[2/2] Evaluating PPO Model...")
ppo_results = run_evaluation(
    model_path=ppo_output_dir,
    output_dir=OUTPUT_DIR,
    eval_name="ppo",
    use_lora=True,
    base_model=MODEL_NAME
)

# ============================================================================
# RESULTS COMPARISON: BASE MODEL vs PPO-TRAINED MODEL
# ============================================================================

print("\n" + "="*70)
print("TRAINING RESULTS COMPARISON")
print("="*70 + "\n")

# Extract metrics
base_perplexity = base_results.get('perplexity', 0.0)
base_rouge = base_results.get('rouge_l', 0.0)
base_bleu = base_results.get('bleu', 0.0)
base_samples = base_results.get('total_samples', 0)

ppo_perplexity = ppo_results.get('perplexity', 0.0)
ppo_rouge = ppo_results.get('rouge_l', 0.0)
ppo_bleu = ppo_results.get('bleu', 0.0)
ppo_samples = ppo_results.get('total_samples', 0)

# Calculate improvements
perplexity_change = ppo_perplexity - base_perplexity
rouge_change = ppo_rouge - base_rouge
bleu_change = ppo_bleu - base_bleu

# Percentage changes
perplexity_pct = ((ppo_perplexity - base_perplexity) / base_perplexity * 100) if base_perplexity != 0 else 0
rouge_pct = ((ppo_rouge - base_rouge) / base_rouge * 100) if base_rouge != 0 else 0
bleu_pct = ((ppo_bleu - base_bleu) / base_bleu * 100) if base_bleu != 0 else 0

print("📊 BASE MODEL RESULTS")
print("-" * 70)
print(f"   Perplexity:    {base_perplexity:.4f}")
print(f"   ROUGE-L:       {base_rouge:.4f}")
print(f"   BLEU:          {base_bleu:.6f}")
print(f"   Total Samples: {base_samples}")

print("\n📊 PPO-TRAINED MODEL RESULTS")
print("-" * 70)
print(f"   Perplexity:    {ppo_perplexity:.4f}")
print(f"   ROUGE-L:       {ppo_rouge:.4f}")
print(f"   BLEU:          {ppo_bleu:.6f}")
print(f"   Total Samples: {ppo_samples}")

print("\n📈 IMPROVEMENT ANALYSIS")
print("-" * 70)

# Perplexity (lower is better)
if perplexity_change < 0:
    print(f"   ✅ Perplexity:    {perplexity_change:.4f} ({perplexity_pct:.2f}%) - IMPROVED")
elif perplexity_change > 0:
    print(f"   ❌ Perplexity:    {perplexity_change:+.4f} ({perplexity_pct:+.2f}%) - DEGRADED")
else:
    print(f"   ➖ Perplexity:    No change")

# ROUGE-L (higher is better)
if rouge_change > 0:
    print(f"   ✅ ROUGE-L:       {rouge_change:+.4f} ({rouge_pct:+.2f}%) - IMPROVED")
elif rouge_change < 0:
    print(f"   ❌ ROUGE-L:       {rouge_change:.4f} ({rouge_pct:.2f}%) - DEGRADED")
else:
    print(f"   ➖ ROUGE-L:       No change")

# BLEU (higher is better)
if bleu_change > 0:
    print(f"   ✅ BLEU:          {bleu_change:+.6f} ({bleu_pct:+.2f}%) - IMPROVED")
elif bleu_change < 0:
    print(f"   ❌ BLEU:          {bleu_change:.6f} ({bleu_pct:.2f}%) - DEGRADED")
else:
    print(f"   ➖ BLEU:          No change")

print("\n" + "="*70)
print("SUMMARY")
print("="*70)

# Overall assessment
improved_metrics = 0
degraded_metrics = 0

if perplexity_change < 0:  # Lower perplexity is better
    improved_metrics += 1
elif perplexity_change > 0:
    degraded_metrics += 1

if rouge_change > 0:  # Higher ROUGE is better
    improved_metrics += 1
elif rouge_change < 0:
    degraded_metrics += 1

if bleu_change > 0:  # Higher BLEU is better
    improved_metrics += 1
elif bleu_change < 0:
    degraded_metrics += 1

print(f"\n   Improved Metrics:  {improved_metrics}/3")
print(f"   Degraded Metrics:  {degraded_metrics}/3")
print(f"   Unchanged Metrics: {3 - improved_metrics - degraded_metrics}/3")

if improved_metrics > degraded_metrics:
    print("\n   🎉 Overall: PPO training IMPROVED model performance!")
elif degraded_metrics > improved_metrics:
    print("\n   ⚠️  Overall: PPO training DEGRADED model performance")
    print("   💡 Consider: Adjusting reward weights, learning rate, or training steps")
else:
    print("\n   ➖ Overall: Mixed results - some metrics improved, some degraded")

